// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxjbjgyrozveudkcytzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4amJqZ3lyb3p2ZXVka2N5dHp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MjYyNDUsImV4cCI6MjA1OTUwMjI0NX0.dk3aNaN4B6ymqJORCXdGJN1vqDQ1Tj7VVcrygqrj_Dg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);